apiVersion: v1
kind: Secret
metadata:
  name: onges-secrets
  namespace: onges-ns
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: "SUBSTITUIR"
  RabbitMq__Host: "rabbitmq"
  RabbitMq__User: "guest"
  RabbitMq__Password: "SUBSTITUIR"