apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: onges-ns
spec:
  replicas: 1
  selector:
    matchLabels: { app: rabbitmq }
  template:
    metadata:
      labels: { app: rabbitmq }
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3.13-management
          ports:
            - { name: amqp, containerPort: 5672 }
            - { name: management, containerPort: 15672 }
          env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef: { name: onges-secrets, key: RabbitMq__Username }
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef: { name: onges-secrets, key: RabbitMq__Password }
